### ISSUE TITLE
snowmelt and sublimation fluxes

### ISSUE THREAD

**Issue by hndiego** [MESH-Model/MESH-Dev#59]
Hello all,

I am interested in snowmelt values (more generally, in the different partitions of streamflow) and I checked the annual values of the variable DRAINSNO which often is larger than the annual snowfall, so I wonder if snowmelt and DRAINSNO are not the same thing (maybe DRAINSNO consider other fluxes also?). There is a way to obtain snowmelt only?

Similarly, there is a way to obtain sublimation only? (I understand it is included in total evaporation).

Many thanks!

**Comment by mee067** [comment]
As we discussed over Slack, I guess the sum of DRAINSNO is more than snowmelt because DRAINSNO can refreeze, pond, or runoff. If it refreezes and then melts again, you will have the same water summed up twice, at least partially. If it ponds, it can runoff or infiltrate. I do not think there is a variable that traces snowmelt separately. Similarly, there is no variable that traces sublimation separately. One additional note for sublimation: There is direct sublimation from snow on the ground or vegetation but if you have activated the blowing snow algorithm, there will be additional sublimation from blown snow. Both are added to ET.

**Comment by mee067** [comment]
@fuadyassin also added: I usually use DRAINSNO to detect snowmelt and to create a logical condition to filter overland flow. So, if there is DRAINSNO on that day and also overland flow, then I consider the overland flow amount as snowmelt runoff.

**Comment by dprincz** [comment]
Closing since it seems inquiry was resolved.
